const root = new URL("../", import.meta.url);
const check = Deno.args.includes("--check");
const lock = JSON.parse(
  await Deno.readTextFile(new URL("wasm.lock.json", root)),
) as {
  artifact: string;
  sha256: string;
  byteLength: number;
  upstream: { wasmAbiVersion: number };
  postProcessing: {
    tool: string;
    binaryenVersion: string;
    flags: string[];
    input: { sha256: string; byteLength: number };
  };
  requiredExports: string[];
  forbiddenExports: string[];
  forbiddenCustomSections: string[];
};
const expectedPostProcessing = {
  tool: "wasm-opt",
  binaryenVersion: "130",
  flags: ["-Oz", "--strip-debug", "--strip-producers"],
};
if (
  JSON.stringify(lock.postProcessing) !==
    JSON.stringify({
      ...expectedPostProcessing,
      input: lock.postProcessing.input,
    })
) {
  throw new Error("unexpected opaque-zig WASM post-processing pipeline");
}
const bytes = await Deno.readFile(new URL(lock.artifact, root));
const sha256 = hex(await crypto.subtle.digest("SHA-256", bytes));
if (bytes.byteLength !== lock.byteLength || sha256 !== lock.sha256) {
  throw new Error(
    `artifact does not match wasm.lock.json: ${bytes.byteLength} bytes, sha256 ${sha256}`,
  );
}

const module = await WebAssembly.compile(bytes);
const imports = WebAssembly.Module.imports(module);
if (imports.length !== 0) {
  throw new Error("production OPAQUE WASM must not import host functions");
}
const exports = new Set(
  WebAssembly.Module.exports(module).map(({ name }) => name),
);
for (const name of lock.requiredExports) {
  if (!exports.has(name)) {
    throw new Error(`artifact is missing production export ${name}`);
  }
}
for (const name of lock.forbiddenExports) {
  if (exports.has(name)) {
    throw new Error(`artifact contains forbidden test export ${name}`);
  }
}
if (exports.size !== lock.requiredExports.length) {
  const unexpected = [...exports].filter((name) =>
    !lock.requiredExports.includes(name)
  );
  throw new Error(
    `artifact has unexpected exports: ${
      unexpected.join(", ") || "duplicate lock entries"
    }`,
  );
}
for (const name of lock.forbiddenCustomSections) {
  if (WebAssembly.Module.customSections(module, name).length !== 0) {
    throw new Error(`artifact contains forbidden custom section ${name}`);
  }
}
const instance = await WebAssembly.instantiate(module);
const version = (instance.exports.version as () => number)();
if (version !== lock.upstream.wasmAbiVersion) {
  throw new Error(
    `artifact ABI is ${version}; expected ${lock.upstream.wasmAbiVersion}`,
  );
}

const artifactId = sha256.slice(0, 16);
const metadata =
  `// Generated by tools/generate_wasm.ts. Safe for browser imports.\n` +
  `/** Pinned opaque-zig WASM ABI version. */\nexport const OPAQUE_WASM_ABI_VERSION: number = ${lock.upstream.wasmAbiVersion};\n` +
  `/** SHA-256 of the uncompressed production artifact. */\nexport const OPAQUE_WASM_SHA256: string = "${sha256}";\n` +
  `/** Byte length of the uncompressed production artifact. */\nexport const OPAQUE_WASM_BYTE_LENGTH: number = ${bytes.byteLength};\n` +
  `/** Short immutable artifact content identifier. */\nexport const OPAQUE_WASM_ARTIFACT_ID: string = "${artifactId}";\n` +
  `/** Build the hash-versioned asset path under an auth prefix. */\nexport const opaqueWasmAssetPath = (prefix: string = "/api/auth"): string => ` +
  '`${prefix.replace(/\\/$/, "")}/opaque.${OPAQUE_WASM_ARTIFACT_ID}.wasm`;\n';

// Ship the verified binary itself: static `import` consumers load this file,
// and the HTTP asset endpoint serves it byte-for-byte.
await verifyOrWriteBytes(new URL("src/opaque.wasm", root), bytes);
await verifyOrWrite(new URL("src/artifact.ts", root), metadata);

async function verifyOrWrite(url: URL, expected: string): Promise<void> {
  if (check) {
    const actual = await Deno.readTextFile(url);
    if (actual !== expected) {
      throw new Error(`${url.pathname} is stale; run deno task artifact`);
    }
  } else {
    await Deno.writeTextFile(url, expected);
  }
}

async function verifyOrWriteBytes(
  url: URL,
  expected: Uint8Array,
): Promise<void> {
  if (check) {
    let actual: Uint8Array;
    try {
      actual = await Deno.readFile(url);
    } catch {
      throw new Error(`${url.pathname} is missing; run deno task artifact`);
    }
    if (
      actual.byteLength !== expected.byteLength ||
      !actual.every((byte, index) => byte === expected[index])
    ) {
      throw new Error(`${url.pathname} is stale; run deno task artifact`);
    }
  } else {
    await Deno.writeFile(url, expected);
  }
}

function hex(value: ArrayBuffer | Uint8Array): string {
  const bytes = value instanceof Uint8Array ? value : new Uint8Array(value);
  return Array.from(bytes, (byte) => byte.toString(16).padStart(2, "0")).join(
    "",
  );
}
