// Generated by tools/generate_wasm.ts. Safe for browser imports.
/** Pinned opaque-zig WASM ABI version. */
export const OPAQUE_WASM_ABI_VERSION: number = 5;
/** SHA-256 of the uncompressed production artifact. */
export const OPAQUE_WASM_SHA256: string = "4d5617817d98628d8db556f30191be1244cc3ba36e277bd08e83e97e3432ec2d";
/** Byte length of the uncompressed production artifact. */
export const OPAQUE_WASM_BYTE_LENGTH: number = 263399;
/** Short immutable artifact content identifier. */
export const OPAQUE_WASM_ARTIFACT_ID: string = "4d5617817d98628d";
/** Build the hash-versioned asset path under an auth prefix. */
export const opaqueWasmAssetPath = (prefix: string = "/api/auth"): string => `${prefix.replace(/\/$/, "")}/opaque.${OPAQUE_WASM_ARTIFACT_ID}.wasm`;
