// Generated by tools/generate_wasm.ts. Safe for browser imports.
/** Pinned opaque-zig WASM ABI version. */
export const OPAQUE_WASM_ABI_VERSION: number = 5;
/** SHA-256 of the uncompressed production artifact. */
export const OPAQUE_WASM_SHA256: string = "f7e0998259991660c3fa5bcff0080d79462e38115b2ac8bc40759bb13d1c4079";
/** Byte length of the uncompressed production artifact. */
export const OPAQUE_WASM_BYTE_LENGTH: number = 263724;
/** Short immutable artifact content identifier. */
export const OPAQUE_WASM_ARTIFACT_ID: string = "f7e0998259991660";
/** Build the hash-versioned asset path under an auth prefix. */
export const opaqueWasmAssetPath = (prefix: string = "/api/auth"): string => `${prefix.replace(/\/$/, "")}/opaque.${OPAQUE_WASM_ARTIFACT_ID}.wasm`;
